apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: pitstop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: registry.gitlab.com/aya03/pitstop_webapp/webapp:98d8859a
          ports:
            - containerPort: 80
